version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: home_expenses
      POSTGRES_USER: jules
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
