# docker/docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - financial-analyzer

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../backend:/app
      - /app/node_modules
      - ../uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/financial-analyzer
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=4000
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - financial-analyzer

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - financial-analyzer

networks:
  financial-analyzer:
    driver: bridge

volumes:
  mongo-data: